Repository AtlasOfLivingAustralia/ala-install, pull requests merged in 2019-05, with the labels that each got.

#271 issue #269 : Java-8 installation on ag-bie-install branch
  ansible/java.yml
  ansible/roles/common/tasks/setfacts.yml
  ansible/roles/exec-jar/tasks/main.yml
  ansible/roles/java/tasks/main.yml
  ansible/roles/java/tasks/openjdk-java-8.yml
  ansible/roles/java/tasks/openjdk-java.yml
  ansible/roles/java/tasks/oracle-java8.yml
  ansible/roles/java/tasks/zulu-8.yml
Labels: IAD, bug

#276 Update download url in nginx
  ansible/roles/biocache-service/tasks/main.yml
Labels: IAD, bug

#245 Fix namematching for "not-ALA" to be like "ALA"
  ansible/roles/nameindex/tasks/main.yml
Labels: IAD, bug

#261 Include userdetails url
  ansible/roles/alerts/templates/alerts-config.properties
Labels: IAD, bug

#263 Added basic mongodb.org role for using with CAS-5
  ansible/roles/mongodb-org/defaults/main.yml
  ansible/roles/mongodb-org/handlers/main.yml
  ansible/roles/mongodb-org/tasks/main.yml
  ansible/roles/mongodb-org/templates/mongod.yml
  ansible/roles/mongodb-org/vars/main.yml
Labels: IAD, enhancement

#264 Userdetails url base fix in yml configuration
  ansible/roles/userdetails/templates/userdetails-config.yml
Labels: IAD, bug

#265 Fix warn in cas-management start because not found log4j2 configuration
  ansible/roles/cas-management/tasks/main.yml
  ansible/roles/cas-management/templates/application.properties
  ansible/roles/cas-management/templates/log4j2.xml
Labels: IAD, bug

#266 Fix some configuration names that makes cas-management not to start
  ansible/roles/cas-management/templates/application.properties
Labels: IAD, bug

#268 Added login/logout CAS urls to collectory config
  ansible/roles/collectory/templates/config/collectory-config.properties
Labels: IAD, bug, security
